### ISSUE TITLE
Typo in documentation

### ISSUE THREAD

**Issue by Seniru** [BirbLanguage/BirbLanguage.github.io#1]
This is not a big issue. There is a typo in 'conditionals' section of your website.

There is a statement called **x *if* floofier than or just as floofy as y**. I suppose it should be **x *is* floofier than or just as floofy as y**.

Thanks!

**Comment by BirbLanguage** [comment]
Thanks for letting me know! That could definitely throw some people off (especially with it being an example), so it's without a doubt worth fixing
